version: '3.9'
services:
  reverse_proxy:
    image: reverse_proxy:latest
    networks: 
      - intranet
    ports:
      - "8080:8080"
  server1:
    image: express_server:latest
    networks:
      - intranet
    environment:
      - PORT=3000
  server2:
    image: express_server:latest
    networks:
      - intranet
    environment:
      - PORT=3001
networks:
  intranet: