apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: {{ .Values.appName}}
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.proxyPort }}
      targetPort: {{ .Values.exposedPort}}
