proxy:
  listen:
    address: 127.0.0.1
    port: 8080
  services:
    - name: my-service
      domain: myhost.com
      lbPolicy: ROUND_ROBIN
      retries: 3
      hosts:
        - address: server1
          port: 3000
          secure: false
        - address: server2
          port: 3001
          secure: false
server:
  port: ${proxy.listen.port}