apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: ClusterIP
  clusterIP: 10.96.0.20
  selector:
    app: {{ .Values.appName}}
  ports:
    - port: {{ .Values.appPort }}
      targetPort: {{ .Values.exposedPort}}
